[package]
name = "reconst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zydis = "4.0.0-beta.2"
serde = "1.0"
serde_json = { version = "1.0", features = [] }